import type { Metadata } from "next";
import "../../../styles/globals.scss";

export const metadata: Metadata = {
  title: "Sujeito Pizza - Cadastre-se",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
