import type { Metadata } from "next";
import "../../styles/globals.scss";

import { AuthProvider } from "../contexts/AuthContext";

export const metadata: Metadata = {
  title: "Sujeito Pizza - Faça seu Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="pt-BR">
        <body>{children}</body>
      </html>
    </AuthProvider>
  );
}
