import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "../../styles/globals.scss";

import { AuthProvider } from "../contexts/AuthContext";

export const metadata: Metadata = {
  title: "Sujeito Pizza - Faça seu Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="pt-BR">
        <body>
          {children}
          <ToastContainer />
        </body>
      </html>
    </AuthProvider>
  );
}
